name: Lint/Build for library-client
on: [push, pull_request]
jobs: 
  build: 
    runs-on: ubuntu-latest

    env:
      project-directory: ./src/library-client/

    strategy:
      matrix: 
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{matrix.node-version}}
      - run: npm ci
        working-directory: ${{env.project-directory}}
      - run: npm run build
        working-directory: ${{env.project-directory}}